## Handling an Exception
Q1. 1,2,4 <br>
Q2.
```
try:
	a=int(input("a: "))
	b=int(input("b: "))
	
	
	# take user inputs a and b and perform arithmetic operations
	if a == 0:
		f = fun1(a)
	c=a+b
	d=a/b
	e=a*b
	print("try successful")

	# print here	
except ZeroDivisionError:
	print("zero division error occurred")
	# print here
except NameError:
	# print here
	print("name error occurred")
except Exception:
	print("exception occurred")
	# print here
def fun1(n):
	print(n)
```
Q3. *Need solution*  <br>
Q4. 1,2,3 <br>